### ISSUE TITLE
{QUESTION] Use of pySMESH

### ISSUE THREAD

**Issue by Jojain** [trelau/pySMESH#3]
Hello, 
I have some interest in using the SMESH module outside of Salome and I found out your python bindings of it.
The readme says it's work in pogress, I would like to know if this is usable yet ?

The readme have mention of pyOCCT, will this binding of SMESH have pyOCCT as a dependency ? 

I am interested in using SMESH with https://github.com/CadQuery/cadquery which uses it's own python bindings for OCCT, would this lead to incompatibility ?

**Comment by trelau** [comment]
You can try it out by using this conda package for now https://anaconda.org/trelau/smesh4pyocct

Eventually this will be replaced by "pysmesh" but that will give you a way to see how/if it works for you. it will be dependent on pyOCCT and I wouldn't expect it to work (out of the box) with cadquery (though i believe they are also using pybind11 so maybe someday it would be possible to make them interchangeable with some extra work)
